import React, { useState, useEffect } from 'react';
import './ContactUs.css';

function ContactUs() {
    return (
        <div>
            <div
                style={{
                    minHeight: "400px",
                    color: "grey"
                }}
            >
                <h1
                style={{
                    color: "purple",
                    fontSize: "40px",
                }}>
                    Contact Us</h1>

                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet cursus sit amet dictum sit amet justo donec. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Sed libero enim sed faucibus turpis in. Elementum tempus egestas sed sed risus pretium quam. Sit amet consectetur adipiscing elit duis. Volutpat diam ut venenatis tellus. Donec enim diam vulputate ut pharetra sit. Quis vel eros donec ac odio tempor. Enim tortor at auctor urna nunc id. Ultrices sagittis orci a scelerisque purus. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.

Bibendum est ultricies integer quis. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Et ultrices neque ornare aenean euismod elementum. Enim neque volutpat ac tincidunt vitae semper quis lectus. In hac habitasse platea dictumst vestibulum rhoncus est. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Magna sit amet purus gravida quis. Tincidunt praesent semper feugiat nibh sed pulvinar. Sit amet facilisis magna etiam tempor orci eu. Ridiculus mus mauris vitae ultricies leo. Blandit turpis cursus in hac habitasse platea dictumst quisque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Malesuada pellentesque elit eget gravida cum. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Enim lobortis scelerisque fermentum dui faucibus.

Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Pulvinar elementum integer enim neque volutpat ac tincidunt. Nunc consequat interdum varius sit amet mattis vulputate. Neque viverra justo nec ultrices dui sapien. Praesent tristique magna sit amet. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Ante in nibh mauris cursus mattis molestie a iaculis at. Pellentesque adipiscing commodo elit at imperdiet. Orci eu lobortis elementum nibh tellus molestie. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Rhoncus mattis rhoncus urna neque viverra. Faucibus et molestie ac feugiat sed. Ac turpis egestas sed tempus urna et pharetra. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Nec feugiat in fermentum posuere. Nibh praesent tristique magna sit amet purus gravida quis. Curabitur vitae nunc sed velit dignissim sodales. Sit amet tellus cras adipiscing enim eu turpis egestas. Adipiscing elit pellentesque habitant morbi. Tempus quam pellentesque nec nam aliquam sem.

Dignissim sodales ut eu sem integer vitae. Suspendisse ultrices gravida dictum fusce. At augue eget arcu dictum varius duis at consectetur. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Amet porttitor eget dolor morbi. Risus in hendrerit gravida rutrum quisque non tellus orci. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Lacus sed viverra tellus in hac habitasse platea. Feugiat sed lectus vestibulum mattis ullamcorper. Nec tincidunt praesent semper feugiat nibh sed. Eget magna fermentum iaculis eu non diam phasellus. Lorem ipsum dolor sit amet consectetur adipiscing. Maecenas sed enim ut sem viverra aliquet eget sit. Senectus et netus et malesuada fames ac turpis egestas. Arcu ac tortor dignissim convallis aenean et tortor. Eget duis at tellus at urna condimentum mattis pellentesque id. Facilisis leo vel fringilla est ullamcorper eget.

Diam ut venenatis tellus in metus vulputate eu. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Arcu cursus euismod quis viverra nibh cras pulvinar. Arcu ac tortor dignissim convallis. Ac ut consequat semper viverra nam. Aliquam id diam maecenas ultricies mi eget mauris. Blandit turpis cursus in hac. Gravida rutrum quisque non tellus orci ac auctor. Massa sapien faucibus et molestie. Purus in massa tempor nec feugiat nisl pretium. Risus viverra adipiscing at in tellus integer. Posuere morbi leo urna molestie at elementum eu facilisis. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Tortor pretium viverra suspendisse potenti nullam. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus.

Fames ac turpis egestas integer eget aliquet nibh. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Non quam lacus suspendisse faucibus interdum posuere. Pharetra et ultrices neque ornare. Euismod quis viverra nibh cras pulvinar mattis nunc. Amet porttitor eget dolor morbi non. Platea dictumst vestibulum rhoncus est pellentesque elit. Pharetra diam sit amet nisl suscipit adipiscing. Aliquet eget sit amet tellus cras adipiscing enim. Odio tempor orci dapibus ultrices. Elit pellentesque habitant morbi tristique senectus et netus. Condimentum id venenatis a condimentum vitae sapien pellentesque. Non sodales neque sodales ut.

Semper eget duis at tellus at. Tortor vitae purus faucibus ornare. Tincidunt praesent semper feugiat nibh sed pulvinar. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Auctor urna nunc id cursus metus aliquam. Maecenas pharetra convallis posuere morbi leo. Id venenatis a condimentum vitae sapien pellentesque. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Sed lectus vestibulum mattis ullamcorper velit. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Lorem donec massa sapien faucibus et molestie ac feugiat. Arcu ac tortor dignissim convallis aenean et tortor at. Volutpat maecenas volutpat blandit aliquam etiam erat. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Ultricies lacus sed turpis tincidunt id. Felis bibendum ut tristique et egestas. Turpis nunc eget lorem dolor sed.

Vulputate odio ut enim blandit volutpat maecenas. Tincidunt augue interdum velit euismod in pellentesque. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Orci porta non pulvinar neque laoreet suspendisse. Lectus proin nibh nisl condimentum id. Fusce id velit ut tortor pretium viverra. Dui sapien eget mi proin sed libero enim sed. Leo integer malesuada nunc vel risus. Elementum integer enim neque volutpat ac tincidunt. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Quis blandit turpis cursus in hac habitasse platea. Dictum varius duis at consectetur. In vitae turpis massa sed elementum tempus egestas sed. Bibendum arcu vitae elementum curabitur.

Mattis aliquam faucibus purus in massa tempor. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Aliquam sem et tortor consequat. Ac tincidunt vitae semper quis. Id ornare arcu odio ut. Sit amet commodo nulla facilisi nullam vehicula. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Arcu dictum varius duis at. Etiam dignissim diam quis enim lobortis scelerisque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. In nulla posuere sollicitudin aliquam ultrices. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Quisque id diam vel quam elementum pulvinar etiam. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Tellus at urna condimentum mattis pellentesque id nibh. Semper risus in hendrerit gravida. Viverra aliquet eget sit amet tellus cras adipiscing.

Aenean sed adipiscing diam donec adipiscing tristique risus. Risus pretium quam vulputate dignissim suspendisse in est. Diam donec adipiscing tristique risus nec feugiat in. Diam quam nulla porttitor massa id neque. Justo donec enim diam vulputate ut. Mi bibendum neque egestas congue quisque egestas diam in arcu. Ac placerat vestibulum lectus mauris ultrices eros. Morbi quis commodo odio aenean sed adipiscing diam donec. Vestibulum rhoncus est pellentesque elit. Orci eu lobortis elementum nibh.

Molestie a iaculis at erat pellentesque. Blandit cursus risus at ultrices. Diam vel quam elementum pulvinar etiam. Massa tincidunt nunc pulvinar sapien et. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Elementum nisi quis eleifend quam adipiscing. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Varius morbi enim nunc faucibus a pellentesque sit. Est placerat in egestas erat imperdiet. Pulvinar mattis nunc sed blandit libero. Donec et odio pellentesque diam volutpat. Tellus integer feugiat scelerisque varius morbi enim. Morbi tempus iaculis urna id volutpat. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula.

Quam quisque id diam vel quam. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Cras tincidunt lobortis feugiat vivamus at augue. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Est ultricies integer quis auctor. At quis risus sed vulputate odio ut. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Eget est lorem ipsum dolor sit amet consectetur. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Ac tincidunt vitae semper quis lectus nulla at volutpat. Gravida cum sociis natoque penatibus et magnis dis parturient montes. At lectus urna duis convallis convallis tellus id interdum. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Quisque sagittis purus sit amet volutpat. In vitae turpis massa sed elementum tempus. Urna neque viverra justo nec ultrices dui. Enim ut sem viverra aliquet eget. Ornare massa eget egestas purus. Dolor morbi non arcu risus quis varius quam.

Hac habitasse platea dictumst quisque sagittis purus sit amet. Amet mattis vulputate enim nulla aliquet. Amet volutpat consequat mauris nunc. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Diam phasellus vestibulum lorem sed risus ultricies. Sagittis purus sit amet volutpat consequat mauris. Tristique senectus et netus et malesuada fames ac. Arcu felis bibendum ut tristique. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Et tortor at risus viverra. Tristique et egestas quis ipsum suspendisse ultrices gravida. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Quisque non tellus orci ac auctor augue mauris. Massa enim nec dui nunc mattis enim ut tellus elementum. Viverra justo nec ultrices dui sapien eget mi proin sed. At erat pellentesque adipiscing commodo elit. Amet facilisis magna etiam tempor.

Id aliquet lectus proin nibh nisl condimentum id venenatis. Dignissim enim sit amet venenatis urna cursus eget nunc. Urna id volutpat lacus laoreet. Pretium lectus quam id leo in vitae turpis. Pellentesque nec nam aliquam sem et. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Vitae purus faucibus ornare suspendisse. Purus sit amet volutpat consequat mauris nunc congue. Eu augue ut lectus arcu bibendum. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed libero enim sed faucibus turpis in eu.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Diam vulputate ut pharetra sit. Cras tincidunt lobortis feugiat vivamus. Tellus in hac habitasse platea. Est velit egestas dui id. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Bibendum est ultricies integer quis. Posuere sollicitudin aliquam ultrices sagittis orci. Justo laoreet sit amet cursus sit amet dictum. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Nulla aliquet enim tortor at auctor urna nunc. Nunc consequat interdum varius sit amet mattis vulputate. Erat imperdiet sed euismod nisi porta lorem mollis. Lacus sed turpis tincidunt id aliquet risus feugiat in ante.

Egestas dui id ornare arcu odio ut sem nulla. Nisi scelerisque eu ultrices vitae auctor eu. Sed sed risus pretium quam vulputate. Viverra nibh cras pulvinar mattis nunc sed blandit. Maecenas sed enim ut sem viverra. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Suspendisse potenti nullam ac tortor vitae purus faucibus. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Diam maecenas sed enim ut sem. Arcu felis bibendum ut tristique et egestas. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Nec ullamcorper sit amet risus nullam eget felis eget. Ornare quam viverra orci sagittis.

Cras semper auctor neque vitae tempus quam. Gravida in fermentum et sollicitudin ac orci phasellus. Elementum facilisis leo vel fringilla est. Venenatis lectus magna fringilla urna. Odio euismod lacinia at quis risus sed. Quisque id diam vel quam. In nibh mauris cursus mattis. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Mi proin sed libero enim sed faucibus turpis in. Egestas diam in arcu cursus euismod quis viverra nibh cras. Nec nam aliquam sem et tortor consequat id porta nibh. Sagittis id consectetur purus ut faucibus. Pharetra convallis posuere morbi leo urna. Auctor urna nunc id cursus metus aliquam. Sagittis purus sit amet volutpat consequat. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Habitant morbi tristique senectus et netus et. Imperdiet massa tincidunt nunc pulvinar. Non arcu risus quis varius quam quisque.

Ullamcorper a lacus vestibulum sed arcu non odio euismod. Lobortis feugiat vivamus at augue eget arcu dictum varius. Adipiscing diam donec adipiscing tristique risus nec. Bibendum ut tristique et egestas quis ipsum suspendisse. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Risus sed vulputate odio ut enim. Eu nisl nunc mi ipsum faucibus vitae aliquet. Diam volutpat commodo sed egestas egestas. Feugiat in ante metus dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada. Commodo elit at imperdiet dui accumsan sit amet. Aliquet nibh praesent tristique magna. Convallis aenean et tortor at risus. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Enim sit amet venenatis urna cursus eget. Tincidunt eget nullam non nisi est. Non consectetur a erat nam. Nunc sed blandit libero volutpat sed cras. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat.

Enim tortor at auctor urna nunc id cursus metus. Pharetra convallis posuere morbi leo. Commodo viverra maecenas accumsan lacus vel facilisis. Sem et tortor consequat id porta nibh venenatis cras sed. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Dictum at tempor commodo ullamcorper. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet cursus sit amet dictum sit amet justo donec. Enim ut tellus elementum sagittis vitae et leo. Eu scelerisque felis imperdiet proin fermentum. Amet porttitor eget dolor morbi non. Dui ut ornare lectus sit amet est placerat in egestas. Vulputate enim nulla aliquet porttitor. Ac turpis egestas integer eget aliquet. Ligula ullamcorper malesuada proin libero nunc. Elit sed vulputate mi sit.

Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Phasellus vestibulum lorem sed risus ultricies tristique. Pretium vulputate sapien nec sagittis aliquam malesuada. Nisi porta lorem mollis aliquam ut porttitor leo a. Elementum nibh tellus molestie nunc non blandit massa enim. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Adipiscing diam donec adipiscing tristique risus. Volutpat maecenas volutpat blandit aliquam etiam. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. At varius vel pharetra vel turpis. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus.
            </div>
        </div>
    );
}

export default ContactUs